package info;

//All the possible subjects a class can be in (taken from 2019 data)
public enum Subject { AHS,ANTH,ARCH,ART,ASTR,BEC,BIOL,BITH,CE,CHEM,CHIN,COMM,CORE,CSCI,
	ECON,EDUC,ENG,ENGL,ENGR,ENGW,ENVR,FREN,GEL,GEND,GEOG,GEOL,GERM,GREK,HEBR,HIST,HNGR,
	IDS,IR,LATN,LING,MATH,MSCI,MUCS,MUEP,MUIP,MUMS,MUTC,NEUR,PACS,PHIL,PHYS,PSCI,PSYC,
	RELI,SCI,SOC,SPAN,SSCI,SWEL,URBN };